apiVersion: v1
kind: Service
metadata:
  name: hello-user-service
  namespace: assignment
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30303
  selector:
    app: hello-app
  type: LoadBalancer
